@extends('layouts.app')

@section('content')
<div class="container-fluid px-0">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-2">
        <div><h3 class="fw-bold mb-1">Kartu Stok Bahan</h3><p class="text-muted mb-0">Riwayat mutasi dan HPP moving average bahan Manufaktur. Halaman ini hanya untuk melihat data.</p></div>
        <div class="d-flex gap-2"><a href="{{ route('mfg.yarns.index') }}" class="btn btn-outline-secondary btn-sm">Master Yarn</a><a href="{{ route('mfg.fabrics.index') }}" class="btn btn-outline-secondary btn-sm">Master Fabric</a><a href="{{ route('mfg.auxiliary-materials.index') }}" class="btn btn-outline-secondary btn-sm">Bahan Penolong</a></div>
    </div>
    <form method="GET" action="{{ route('mfg.material-ledger.index') }}" class="card shadow-sm border-0 mb-3"><div class="card-body"><div class="row g-2 align-items-end">
        <div class="col-md-2"><label class="form-label">Jenis Bahan</label><select name="item_type" class="form-select" onchange="this.form.submit()"><option value="YARN" @selected($type === 'YARN')>Yarn</option><option value="FABRIC" @selected($type === 'FABRIC')>Fabric</option><option value="AUXILIARY" @selected($type === 'AUXILIARY')>Bahan Penolong</option></select></div>
        <div class="col-md-4"><label class="form-label">Material</label><select name="item_id" class="form-select" required>@forelse($materials as $material)<option value="{{ $material->id }}" @selected($itemId == $material->id)>{{ $material->yarn_code ?? $material->fabric_code ?? $material->material_code }} — {{ $material->description ?? $material->material_name ?? $material->yarn_type ?? $material->fabric_type }}</option>@empty<option value="">Belum ada material</option>@endforelse</select></div>
        <div class="col-md-2"><label class="form-label">Dari Tanggal</label><input type="date" name="start_date" class="form-control" value="{{ $startDate }}"></div><div class="col-md-2"><label class="form-label">Sampai Tanggal</label><input type="date" name="end_date" class="form-control" value="{{ $endDate }}"></div><div class="col-md-2"><button class="btn btn-primary w-100">Tampilkan</button></div>
    </div></div></form>
    <div class="card shadow-sm border-0"><div class="card-header bg-white d-flex justify-content-between"><div><b>{{ $selectedMaterial?->yarn_code ?? $selectedMaterial?->fabric_code ?? $selectedMaterial?->material_code ?? 'Pilih material' }}</b><span class="text-muted"> — {{ $selectedMaterial?->description ?? $selectedMaterial?->material_name ?? $selectedMaterial?->yarn_type ?? $selectedMaterial?->fabric_type }}</span></div><div>HPP saat ini: <b>Rp {{ number_format($selectedMaterial?->average_cost ?? 0, 2) }}</b> · Stok saat ini: <b>{{ number_format($selectedMaterial?->stock_quantity ?? 0, 2) }} {{ $selectedMaterial?->unit }}</b></div></div><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>Tanggal</th><th>No. Bukti</th><th>Keterangan</th><th class="text-end">Masuk</th><th class="text-end">Keluar</th><th class="text-end">HPP Unit</th><th class="text-end">Nilai Mutasi</th><th class="text-end">Saldo Qty</th><th class="text-end">Saldo Nilai</th><th class="text-end">MAC</th></tr></thead><tbody>
        @forelse($ledgers as $ledger)<tr><td>{{ $ledger->transaction_date->format('d/m/Y') }}</td><td><span class="badge bg-light text-dark border">{{ $ledger->evidence_number }}</span></td><td>{{ $ledger->description }}</td><td class="text-end text-success fw-bold">{{ $ledger->type === 'IN' ? number_format($ledger->qty, 2) : '-' }}</td><td class="text-end text-danger fw-bold">{{ $ledger->type === 'OUT' ? number_format($ledger->qty, 2) : '-' }}</td><td class="text-end">Rp {{ number_format($ledger->unit_cost, 2) }}</td><td class="text-end">Rp {{ number_format($ledger->total_cost, 2) }}</td><td class="text-end fw-bold">{{ number_format($ledger->running_qty, 2) }}</td><td class="text-end fw-bold">Rp {{ number_format($ledger->running_value, 2) }}</td><td class="text-end">Rp {{ number_format($ledger->moving_average_cost, 2) }}</td></tr>
        @empty <tr><td colspan="10" class="text-center text-muted py-4">Belum ada mutasi bahan pada periode yang dipilih.</td></tr>
        @endforelse
    </tbody></table></div></div>
</div>
@endsection